#!/bin/ash

# GPL $Id: network,v 1.3 2005/10/09 16:39:04 cvonk Exp $
# system init for network

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
    start)
        echo "Starting network..."
        hostname `cat /etc/hostname`
        /sbin/ifup -a
        ;;
    stop)
        echo -n "Stopping network..."
        /sbin/ifdown -a
        ;;
    restart)
        "$0" stop
        "$0" start
        ;;
    status)
        ip address
        ip route
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit $?

